# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown

# Skip issues and pull requests created before a given timestamp. Timestamp must
# follow ISO 8601 (`YYYY-MM-DD`). Set to `false` to disable
#skipCreatedBefore: false

# Issues and pull requests with these labels will be ignored. Set to `[]` to disable
#exemptLabels: []

# Comment to post before closing or locking. Set to `false` to disable
#comment: true

# Label to add before closing or locking. Set to `false` to disable
#label: true

# Close issues and pull requests
#close: true

# Lock issues and pull requests
#lock: true

# Limit to only `issues` or `pulls`
#only: pulls

# Optionally, specify configuration settings just for `issues` or `pulls`
issues:
   comment: >
     This repository is only a mirror of https://gitlab.com/KevinRoebert/ClearUrls. Issues are read here, but it can take longer until they are addressed. If possible, please use the GitLab repo or this support mail address: support (at) clearurls.xyz.
   lock: false
   close: false

pulls:
   comment: >
     This repository is just a mirror of https://gitlab.com/KevinRoebert/ClearUrls. Only there pull requests accepted.   
   lock: false
   close: true

# Repository to extend settings from
# _extends: repo
